create table systems (
  id SERIAL PRIMARY KEY,
  sysnr VARCHAR(4) NOT NULL,
  descr TEXT NOT NULL
);

CREATE TABLE notifications (
        id SERIAL PRIMARY KEY,
        meldung CHARACTER VARYING(8) NOT NULL,
        auftrag CHARACTER VARYING(9) NOT NULL,
        turnaround_nr_ CHARACTER VARYING(14) NOT NULL,
        beschreibung CHARACTER VARYING(40) NOT NULL,
        meldender CHARACTER VARYING(12) NOT NULL,
        verantw_arbeitspl_ CHARACTER VARYING(18) NOT NULL,
        zusaetzl__bemerk_1 CHARACTER VARYING(24) NOT NULL,
        zusaetzl__bemerk_2 CHARACTER VARYING(17) NOT NULL,
        zusaetzl__bemerk_3 CHARACTER VARYING(23) NOT NULL,
        technische_identnummer CHARACTER VARYING(22) NOT NULL,
        rui_schema_nr_ CHARACTER VARYING(38) NOT NULL,
        moc_nr_ CHARACTER VARYING(12) NOT NULL,
        standort_besonderheit_1 CHARACTER VARYING(23) NOT NULL,
        standort_besonderheit_2 CHARACTER VARYING(70) NOT NULL,
        planung_fuehrender CHARACTER VARYING(17) NOT NULL,
        planung_2 CHARACTER VARYING(9) NOT NULL,
        ansprechpartner_betrieb CHARACTER VARYING(23) NOT NULL,
        ansprechpartner_technik CHARACTER VARYING(23) NOT NULL,
        rohrleitungs_nr CHARACTER VARYING(27) NOT NULL,
        psp_element CHARACTER VARYING(11) NOT NULL,
        meldungsdatum CHARACTER VARYING(16) NOT NULL,
        prio__planung CHARACTER VARYING(13) NOT NULL,
        planung_text CHARACTER VARYING(12) NOT NULL,
        anlagen_system CHARACTER VARYING(14) NOT NULL,
        baufeld_gebaeude CHARACTER VARYING(15) NOT NULL,
        kostenschaetzung CHARACTER VARYING(15) NOT NULL,
        auftstatus       CHARACTER VARYING(39) NOT NULL,
        userstatus       CHARACTER VARYING(15) NOT NULL,
        codierung        CHARACTER VARYING(29) NOT NULL,
        meldsys_status  CHARACTER VARYING(14) NOT NULL,
        angelegt_von    CHARACTER VARYING(12) NOT NULL,
        angelegt_am     CHARACTER VARYING(16) NOT NULL,
        geaendert_am    TEXT NOT NULL,
        geaendert_von  TEXT NOT NULL,
        floc_nr TEXT NOT NULL,
        meldungsart TEXT NOT NULL,
        equipment TEXT NOT NULL,
        floc TEXT NOT NULL,
        anre_import_lfdnr CHARACTER VARYING(3) NOT NULL,
        anre_file_datum CHARACTER VARYING(38) NOT NULL
);